name: DangerJS
on: pull_request

jobs:
  dangerCI:
    name: dangerCI analysis
    env:
      DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure node environment
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Clean install dependencies
        run: npm ci
      - name: Danger
        run: npm run danger:ci